# Generated by Django 6.0.2 on 2026-03-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mood',
            field=models.CharField(choices=[('happy', '😊 嬉しい'), ('normal', '😐 普通'), ('sad', '😢 悲しい')], default='normal', max_length=10),
        ),
    ]
